### ISSUE TITLE
Use the six package to support Python 2.x ?

### ISSUE THREAD

**Issue by tsani** [Brightspace/valence-sdk-python#2]
The only specifically Python 3.x functionality used by the SDK is the urllib library which changed between 2.x and 3.x. The six compatibility library provides a Python2/3 agnostic urllib that appears to work fine for the API endpoints that I've used so far. A [fork](https://github.com/parth115/valence-sdk-python) by @parth115  implements this change.

What do you think about merging this in?

**Comment by ViktorHaag** [comment]
I will have a look at it when I return to the office next week. Rather than use `six`, I may take @parth115's work and use `future` instead; I have used it for other projects, and prefer it a bit.

**Comment by ViktorHaag** [comment]
Now supports Py2.7+ via `future`.
