### ISSUE TITLE
ValueError: path contains invalid characters for URL path

### ISSUE THREAD

**Issue by neverendingqs** [Brightspace/valence-sdk-python#6]
https://community.brightspace.com/devcop/f_technical/valueerror_path_contains_invalid_characters_for_url_path

**Comment by ViktorHaag** [comment]
Working as designed:

`UserContext.create_authenticated_url(api_route, method)` needs only an API route as input, not an APIURL (i.e. a full URL containing the host, API route, and query parameters pre-packaged for calling).

With an APIURL (such as one gets in paged data sets), you need to use [`UserContext.decorate_url_with_authentication(url, method)` ](http://docs.valence.desire2learn.com/clients/python/auth.html#d2lvalence.auth.D2LUserContext.decorate_url_with_authentication) instead.
